### ISSUE TITLE
The upcommerce service doesn't start on codespaces default environment

### ISSUE THREAD

**Issue by pezzu** [pezzu/sre-week-two#1]
Codespaces default environment has only 1 CPU available while service requests 10:

deployment.yml:

```yml
containers:
   - name: upcommerce
       ...
       resources:
       limits:
           cpu: "10"
```
